sonar.organization=Nikita Thakre
sonar.projectKey=nikitathakre14
sonar.projectName=Todo
sonar.sources=src
sonar.tests=tests
sonar.coverageReportPaths=coverage.xml  # Adjust based on your coverage tool
