name: SonarCloud Scan

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or your project's Java version
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectKey: nikitathakre14_Todo
          organization: nikitathakre14
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
